# Python NumPy

NumPy (short for Numerical Python) is an open source Python library for doing scientific computing with Python.

It gives an ability to create multidimensional array objects and perform faster mathematical operations. The library contains a long list of useful mathematical functions, including some functions for linear algebra and complex mathematical operations such as Fourier Transform (FT) and random number generator (RNG).

Most of the other libraries that we use in data analytics with Python, such as scikit-learn, SciPy (Scientific Library) and Pandas use some of NumPy's features.

## Create Numpy Arrays

To create a NumPy array we need to pass list of element values inside a square bracket as an argument to the np.array() function.

A 3d array is a matrix of 2d array. A 3d array can also be called as a list of lists where every element is again a list of elements.

In [3]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print('---------------')
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print('---------------')
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)

[1 2 3 4 5 6]
---------------
[[1 2 3]
 [4 5 6]]
---------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print("-" * 10)

----------


In [ ]:
print(a)
 
print("-" * 10)
print(b)
 
print("-" * 10)
print(c)

[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a1 = [1, 2, 3, 4, 5, 6]
print(type(a1))

b1=np.array(a1)
print(type(b1))

<class 'list'>
<class 'numpy.ndarray'>


### Attributes
The main data structure for multidimensional arrays in NumPy is the ndarray class. Basic Attributes of the ndarray Class is 
as follow:

Attributes
    1. Shape  - A tuple that specifies the number of elements for each dimension of the array.
    2. Size   - The total number elements in the array.
    3. Ndim   - Determines the dimension an array.
    4. nbytes - Number of bytes used to store the data.
    5. dtype  - Determines the datatype of elements stored in array.

### Shape of an array
The shape method determines the shape of NumPy array in form of (m, n) i.e (no. of rows) x (no. of columns).

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

print(c.size)

(6,)
(2, 3)
(2, 2, 3)
12


In [ ]:
d=np.array([[1],[2],[3],[4],[5],[6]])
d.shape

(6, 1)

### Dimension of an array
The ndim method determines the dimension of NumPy array.

In [ ]:
print(a.ndim) 
print(b.ndim) 
print(c.ndim) 

1
2
3


## Data Types in NumPy

The **dtype method** determines the datatype of elements stored in NumPy array. 
We can also explicitly define the data type using the dtype option as an argument of array function.



In [7]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5, 6])
b1 = np.array([1.5, 2.5, 0.5, 6])
c1 = np.array(['a', 'bat', 'c'])
d1 = np.array([555, 666], dtype=float)

In [8]:
print(a1.dtype)
print(b1.dtype)
print(c1.dtype)
print(d1.dtype) 

print(c1)

int64
float64
<U3
float64
['a' 'bat' 'c']


In [10]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


### Reshape an array
The reshape () method modifies existing shape but original array remains unchanged.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a1 = a.reshape(2, 4)
print(a1)
 
print("-" * 10)
a2 = a.reshape(4, 2)
print(a2)
 
print("-" * 10)
a3 = a.reshape(8, 1)
print(a3)

[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Special NumPy functions for generating arrays

### Arrays with arange()
The arange() function creates an array with evenly spaced values between the specified start, end, and increment values.

np.arange(Start, End, Increment)

In [ ]:
a = np.arange(5) 
print(a)

[0 1 2 3 4]


In [ ]:
b = np.arange(0, 12, 2)
print(b)

[ 0  2  4  6  8 10]


In [ ]:
b1 = np.arange(1, 12, 2)
b1

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
c = np.arange(0, 12, 2).reshape(2, 3)
print(c)

[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
d = np.arange(9).reshape(3, 3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Arrays with linspace()
The linspace() function generates an array with evenly spaced values between specified start and end values, 
using a specified number of elements.

np.linspace(Start, End, Number of elements)

In [ ]:
a = np.linspace(1, 12, 4)
print(a)

print("")

b = np.linspace(1, 12, 12).reshape(4, 3)
print(b)

[ 1.          4.66666667  8.33333333 12.        ]

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


### Zero Array
The zeros() function, generates an array with the specified dimensions and data type that is filled with zeros.

In [ ]:
a = np.zeros(3)
print(a)
print("") 
b = np.zeros((2, 4))
print(b)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### One Array
The ones() function, generates an array with the specified dimensions and data type that is filled with ones.

In [ ]:
a = np.ones(3)
print(a)
print("")
b = np.ones((2, 4))
print(b)

[1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Eye Array
The eye() function, returns an array where all elements are equal to zero, except for the k-th diagonal, 
whose values are equal to one.

In [ ]:
a = np.eye(3, dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Random Number Array

The np.random.rand method, generates an array with random numbers that are uniformly distributed.

The np.random.randn method, generates an array with random numbers that are normally distributed.

The np.random.randint method, generates an array with random numbers that are uniformly distributed between 0 and given integer.

In [11]:
print(np.random.rand(3))  
print(np.random.rand(3,2))

[0.62561396 0.31895387 0.35112444]
[[0.61748906 0.94563274]
 [0.98532798 0.01266518]
 [0.70254782 0.27629297]]


In [ ]:
print(np.random.randn(3,2))

[[ 0.90612234  0.6472573 ]
 [ 1.15378512 -0.41789926]
 [ 1.95925096  0.51339728]]


In [ ]:
#print(np.random.randint(2, size=10))
print(np.random.randint(5, size=(2, 4)))

[[3 4 4 0]
 [3 2 0 2]]


In [ ]:
a=np.array([1,2,3])
a.max()

3