# Operations on NumPy Arrays


## Indexing and Slicing

In order to access a single or multiple items of an array, we need to pass array of indexes in square brackets.

Indexing in two-dimensional array is represented by a pair of values, where the first value is the index of the row and the second is the index of the column.

Slicing allows to extract portions of an array or select a subset of an existing array to generate new arrays. For slicing a sequence of numbers are separated by colons (:) within square brackets.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
#print(a[5])   # Get first value
print(a[-1])  # Get last value
#print(a[3])   # Get 4th value from first
#print(a[-5])  # Get 5th value from last

6


In [ ]:
print(a[1:])
#print(a[:-1])
#print(a[2:5])

[2 3 4 5 6]


In [ ]:
# Get multiple values
print(a[[1, -2, -1]])

[2 5 6]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

print("-" * 10)
 
#print(b[0, 2])   # Get first row third col
 
print(b[1, 1:])   # Get second row second and third col

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[5 6]


## Arithmetic Operations

The arithmetic operations with NumPy arrays perform element-wise operations, this means the operators are applied only between corresponding elements.

In [3]:
import numpy as np
a = np.array([[10, 20, 30], [40, 50, 60]])
 
print(a + 2)
print("")
 
print(a - 5)
print("")
 
print(a * 2)
print("")
 
print(a / 5)
print("")
 
print(a ** 2)
print("")


print(np.sqrt(a))

[[12 22 32]
 [42 52 62]]

[[ 5 15 25]
 [35 45 55]]

[[ 20  40  60]
 [ 80 100 120]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]]

[[ 100  400  900]
 [1600 2500 3600]]

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


## Elementary Mathematical Functions

These mathematical functions take a single array of any dimension as input and returns a new array of the same shape.


Functions
    1. np.cos(), np.sin(), np.tan()             - Trigonometric functions.
    2. np.arccos(), np.arcsin(), np.arctan()	- Inverse trigonometric functions.
    3. np.cosh(), np.sinh(), np.tanh()	        - Hyperbolic trigonometric functions.
    4. np.arccosh(), np.arcsinh(), np.arctanh() - Inverse hyperbolic trigonometric unctions.
    5. np.sqrt()	                            - Square root.
    6. np.exp()                                 - Exponential.
    7. np.log(), np.log2(), np.log10()          - Logarithms of base e, 2, and 10, respectively.

## Element-wise Mathematical Operations
np.add(), np.subtract(), np.multiply(), np.divide(), np.round(), np.power

In [ ]:
a=np.array([1,2,3])
b=np.array([3,2,1])
c=a+b
print(c)

print("")

d=np.add(a,b)
print(d)

[4 4 4]

[4 4 4]


## Aggregate and Statistical Functions
np.mean(), np.std(), np.var(), np.sum(), np.prod(), np.cumsum(), np.cumprod(), np.min(), np.max()

In [ ]:
a=[3,7,9,1]
print(np.max(a))
print(np.mean(a))

9
5.0
